// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKtNTFfyg4OT3V1mQk_Ofa5H23pTNjrEo',
    appId: '1:818107601225:web:f42e63982aa6fbb43f8a98',
    messagingSenderId: '818107601225',
    projectId: 'chattingapp-2378e',
    authDomain: 'chattingapp-2378e.firebaseapp.com',
    storageBucket: 'chattingapp-2378e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvCdrgLjVFFK_qEnebrGaibW_bIDvSRyI',
    appId: '1:818107601225:android:380cfa3fcf13d68c3f8a98',
    messagingSenderId: '818107601225',
    projectId: 'chattingapp-2378e',
    storageBucket: 'chattingapp-2378e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4mwWr_PS3mpEOr73odVbeM1i5sMVZAnI',
    appId: '1:818107601225:ios:0ffbd74094683b313f8a98',
    messagingSenderId: '818107601225',
    projectId: 'chattingapp-2378e',
    storageBucket: 'chattingapp-2378e.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4mwWr_PS3mpEOr73odVbeM1i5sMVZAnI',
    appId: '1:818107601225:ios:0ffbd74094683b313f8a98',
    messagingSenderId: '818107601225',
    projectId: 'chattingapp-2378e',
    storageBucket: 'chattingapp-2378e.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKtNTFfyg4OT3V1mQk_Ofa5H23pTNjrEo',
    appId: '1:818107601225:web:f821883f42d4e4433f8a98',
    messagingSenderId: '818107601225',
    projectId: 'chattingapp-2378e',
    authDomain: 'chattingapp-2378e.firebaseapp.com',
    storageBucket: 'chattingapp-2378e.firebasestorage.app',
  );
}
